name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Create new branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "doxygen-bot"
          git checkout -b update-doxygen-documentation

      - name: Clone external repository
        run: |
          git clone https://github.com/sinricpro/esp8266-esp32-sdk

      - name: Install Doxygen
        run: |
          sudo apt-get install -y doxygen graphviz

      - name: Generate Documentation
        run: |
          doxygen Doxyfile

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update Doxygen documentation" || echo "No changes to commit"
          git pull --rebase origin master
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-doxygen-documentation

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Doxygen documentation
          title: 'Update Doxygen documentation'
          body: 'This PR updates the Doxygen documentation.'
          branch: update-doxygen-documentation
          base: main
